### ISSUE TITLE
Why should I use cognomen?

### ISSUE THREAD

**Issue by azdanov** [ItinerisLtd/cognomen#3]
I've read the readme, but could not understand what's the usecase for this package.
Maybe an example would be helpful? Although I did understand that this is more of an advanced feature.

PS: I'm rather new to WordPress and Roots stack.

**Comment by tangrufus** [comment]
> what's the usecase for this package.

Being lazy!!!

---

### Long answer

By default, you can ssh into your WordPress servers and run wp cli commands:
```sh-session
$ ssh web@111.222.333
$ cd /srv/www/exmaple/current
$ wp plugin list
```

But developers are lazy so wp cli allow us to *inline* the ssh command
```sh-session
$ wp --ssh=web@111.222.333/srv/www/exmaple/current plugin list
```
See: https://make.wordpress.org/cli/handbook/running-commands-remotely/

But but most developers are very lazy so wp cli allow us to *alias* the ssh command

```yaml
# Add these lines into wp-cli.yml so that we can forget it
@example:
  ssh: admin@example.com/srv/www/example.com/current
```

```sh-session
$ wp @example plugin list
```

See:  https://roots.io/guides/using-wp-cli-aliases/

But but but I am lazier than most developers so `cognomen` generates the yaml part for me:

`$ npx @itinerisltd/cognomen` generates [`wp-cli.cognomen.yml`](https://github.com/ItinerisLtd/cognomen/blob/22ef33777be3ffd845bfe048ff0847e6a54f668a/templates/alias.yml.j2) according to Trellis config (host ip, ssh port, username, etc). 

Then, as mentioned in the readme, tell wp cli to *include* `wp-cli.cognomen.yml`
```yaml
# wp-cli.yml OR wp-cli.local.yml
_:
  inherit: wp-cli.cognomen.yml
```

```sh-session
$ wp @myTrellisEnv plugin list
```

With `cognomen`, whenever I add new Trellis enviroment, change server IP, ssh port or linux username, I can update all my wp cli aliases with 1 single command - `$ npx @itinerisltd/cognomen`.

You know how painful it is when you have 12 enviroments under 1 Trellis repo.

**Comment by azdanov** [comment]
@TangRufus Awesome answer, thanks!
